- name: Play - Install and configure Nginx as a LoadBalancer
  hosts: loadbalancer
  tasks:
    - name: Update cache
      apt: update_cache=yes   
    - name: Install Nginx
      apt:
        name: nginx
        state: latest
      become: yes
      # I'm going to need to update the path or I can make this directory structure in the root directory
    - name: Copy the Nginx config file to /etc/nginx/sites-available
      copy:
        src: ${PWD}/nginx-configs/nginx.cfg        
        dest: /etc/nginx/sites-available
      become: yes
    - name: Create symlink of the config file at /etc/nginx/sites-enabled
      file:
        src: /etc/nginx/sites-available/nginx.cfg
        dest: /etc/nginx/sites-enabled
        state: link
      become: yes
    - name: Restart nginx to apply changes
      service:        
        name: nginx        
        state: restarted      
      become: yes
      register: server_status
    - name: Check if Nginx is succesfully installed
      debug:
        msg: "{{server_status}}"