# Name: Brian Meta
# UCID: 30142390
# Course: ENSF 400
# Section: L01, B01
# Assignment 2

# Uninstall Nginx
- name: Play - Uninstall Nginx
  hosts: localhost
  become: yes
  tasks: 
    - name: Uninstall Nginx
      apt: name=nginx state=absent